---
apiVersion: v1
kind: Service
metadata:
  name: APPLICATION_NAME
spec:
  selector:
    app: APPLICATION_NAME
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: APPLICATION_NAME
  labels:
    app: APPLICATION_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPLICATION_NAME
  template:
    metadata:
      labels:
        app: APPLICATION_NAME
    spec:
      containers:
        - name: APPLICATION_NAME
          image: REGISTRY_URL/PROJECT_NAME/APPLICATION_NAME:IMAGE_TAG
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          env:
            - name: runmode
              value: "prod"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080